
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/ST/STM32CubeCLT_1.19.0/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
